services:
  - type: web
    name: miniflux-rss-app
    env: docker
    dockerContext: ./panfleto-core
    dockerfilePath: ./panfleto-core/packaging/docker/alpine/Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: RUN_MIGRATIONS
        value: "1"
      - key: CREATE_ADMIN
        value: "1"
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: OAUTH2_PROVIDER
        value: "oidc"
      - key: OAUTH2_CLIENT_ID
        sync: false
      - key: OAUTH2_CLIENT_SECRET
        sync: false
      - key: OAUTH2_REDIRECT_URL
        value: "https://app.panfleto.win/oauth2/oidc/callback"
      - key: OAUTH2_OIDC_DISCOVERY_ENDPOINT
        sync: false
      - key: OAUTH2_OIDC_PROVIDER_NAME
        value: "Auth0"
      - key: OAUTH2_USER_CREATION
        value: "1"

  - type: web
    name: panfleto-landing
    env: node
    buildCommand: cd landing-page && npm install && npm run build
    startCommand: cd landing-page && npm run start
    plan: free
    region: oregon
    envVars:
      - key: MINIFLUX_API_URL
        value: "https://app.panfleto.win/v1"
      - key: MINIFLUX_ADMIN_USERNAME
        fromService:
          type: web
          name: miniflux-rss-app
          envVarKey: ADMIN_USERNAME
      - key: MINIFLUX_ADMIN_PASSWORD
        fromService:
          type: web
          name: miniflux-rss-app
          envVarKey: ADMIN_PASSWORD
